export const skills = [
  { name: "HTML5" },
  { name: "CSS" },
  { name: "CSS-Grid" },
  { name: "Flex Box" },
  { name: "SCSS/SASS" },
  { name: "Styled Components" },
  { name: "Tailwind" },
  { name: "JavaScript" },
  { name: "React" },
  { name: "Redux" },
  { name: "Redux Toolkit" },
  { name: "REST API" },
  { name: "Framer Motion" },
  { name: "Goggle ReCAPTCHA" },
  { name: "Email JS" },
  { name: "Axios" },
  { name: "Formik" },
  { name: "Slick Carousel" },
  { name: "Swiper" },
  { name: "Chart.js" },
  { name: "Date Fns" },
  { name: "i18n" },
  { name: "React Datepicker" },
  { name: "Yup" },
  { name: "Git" },
  { name: "Responsive/Adaptive Design" },
];
